"use client";

import { useCallback, useEffect, useState } from "react";
import Header from "@/components/header";
import SetupAlert from "@/components/setup-alert";
import ErrorAlert from "@/components/error-alert";
import StepIndicator from "@/components/step-indicator";
import ConnectCard from "@/components/connect-card";
import InputCard from "@/components/input-card";
import ProcessingCard from "@/components/processing-card";
import ResultsView from "@/components/results-view";
import PrivacyNotice from "@/components/privacy-notice";
import {
  getToken,
  getStoredProfile,
  clearToken,
  createPkcePair,
  generateRandomString,
  buildAuthorizeUrl,
  getMe,
} from "@/lib/spotify";
import { clientId, redirectUri } from "@/lib/env";
import { runCreatePlaylistFlow } from "@/lib/helpers";
import type {
  Step,
  ProcessingPhase,
  MatchResult,
  Progress,
  AuthSnapshot,
} from "@/lib/types";

const initialAuth: AuthSnapshot = {
  isConnected: false,
  profile: null,
  step: "connect",
};

export default function Paste2PlaylistClient() {
  const [auth, setAuth] = useState<AuthSnapshot>(initialAuth);
  const [albumInput, setAlbumInput] = useState("");
  const [playlistName, setPlaylistName] = useState("My Albums");
  const [playlistDescription, setPlaylistDescription] = useState(
    "Generated by Paste2Playlist"
  );
  const [isPublic, setIsPublic] = useState(false);

  const [processingPhase, setProcessingPhase] =
    useState<ProcessingPhase>("parsing");
  const [progress, setProgress] = useState<Progress>({
    current: 0,
    total: 0,
    label: "",
  });
  const [matchResults, setMatchResults] = useState<MatchResult[]>([]);

  const [playlistUrl, setPlaylistUrl] = useState("");
  const [totalTracks, setTotalTracks] = useState(0);
  const [error, setError] = useState("");

  const setStep: React.Dispatch<React.SetStateAction<Step>> = useCallback(
    (next) => {
      setAuth((prev) => ({
        ...prev,
        step: typeof next === "function" ? next(prev.step) : next,
      }));
    },
    []
  );

  useEffect(() => {
    const token = getToken();
    const storedProfile = getStoredProfile();

    if (!token || !storedProfile) return;

    queueMicrotask(() => {
      setAuth({ isConnected: true, profile: storedProfile, step: "input" });
    });

    getMe(clientId)
      .then((fresh) => {
        queueMicrotask(() => {
          setAuth({ isConnected: true, profile: fresh, step: "input" });
        });
      })
      .catch(() => {
        clearToken();
        queueMicrotask(() => setAuth(initialAuth));
      });
  }, []);

  const handleConnect = useCallback(async () => {
    if (!clientId || !redirectUri) {
      setError(
        "Missing Spotify configuration. Please set NEXT_PUBLIC_SPOTIFY_CLIENT_ID and NEXT_PUBLIC_SPOTIFY_REDIRECT_URI."
      );
      return;
    }

    const { verifier, challenge } = await createPkcePair();
    const state = generateRandomString(16);

    sessionStorage.setItem("spotify_code_verifier", verifier);
    sessionStorage.setItem("spotify_auth_state", state);

    const authUrl = buildAuthorizeUrl(clientId, redirectUri, state, challenge);
    window.location.href = authUrl;
  }, []);

  const handleDisconnect = useCallback(() => {
    clearToken();
    setAuth(initialAuth);
    setAlbumInput("");
    setMatchResults([]);
    setPlaylistUrl("");
    setTotalTracks(0);
    setError("");
    setProcessingPhase("parsing");
    setProgress({ current: 0, total: 0, label: "" });
  }, []);

  const handleCreatePlaylist = useCallback(() => {
    void runCreatePlaylistFlow({
      albumInput,
      profile: auth.profile,
      playlistName,
      playlistDescription,
      isPublic,
      clientId,
      setError,
      setStep,
      setProcessingPhase,
      setMatchResults,
      setProgress,
      setTotalTracks,
      setPlaylistUrl,
    });
  }, [
    albumInput,
    auth.profile,
    playlistName,
    playlistDescription,
    isPublic,
    setStep,
  ]);

  return (
    <>
      <Header
        isConnected={auth.isConnected}
        profile={auth.profile}
        onDisconnect={handleDisconnect}
      />

      <div className="container mx-auto max-w-2xl px-4 py-8">
        {!auth.isConnected && <SetupAlert />}
        <ErrorAlert message={error} />

        <StepIndicator step={auth.step} isConnected={auth.isConnected} />

        {auth.step === "connect" && <ConnectCard onConnect={handleConnect} />}

        {auth.step === "input" && (
          <InputCard
            albumInput={albumInput}
            setAlbumInput={setAlbumInput}
            playlistName={playlistName}
            setPlaylistName={setPlaylistName}
            playlistDescription={playlistDescription}
            setPlaylistDescription={setPlaylistDescription}
            isPublic={isPublic}
            setIsPublic={setIsPublic}
            onCreate={handleCreatePlaylist}
          />
        )}

        {auth.step === "processing" && (
          <ProcessingCard
            processingPhase={processingPhase}
            progress={progress}
            matchResults={matchResults}
          />
        )}

        {auth.step === "results" && (
          <ResultsView
            matchResults={matchResults}
            playlistUrl={playlistUrl}
            totalTracks={totalTracks}
            createAnotherHref="/"
          />
        )}

        <PrivacyNotice />
      </div>
    </>
  );
}
