"use client";

import { useCallback, useEffect, useState, type SetStateAction } from "react";
import Header from "@/components/header";
import Hero from "@/components/hero";
import ErrorAlert from "@/components/error-alert";
import StepIndicator from "@/components/step-indicator";
import ConnectButton from "@/components/connect-button";
import InputCard from "@/components/input-card";
import ProcessingCard from "@/components/processing-card";
import ResultsView from "@/components/results-view";
import {
  getToken,
  getStoredProfile,
  clearToken,
  createPkcePair,
  generateRandomString,
  buildAuthorizeUrl,
  getMe,
} from "@/lib/spotify";
import { clientId, redirectUri } from "@/lib/env";
import { runCreatePlaylistFlow } from "@/lib/helpers";
import type {
  ProcessingPhase,
  MatchResult,
  Progress,
  AuthSnapshot,
  InputMode,
  Step,
} from "@/lib/types";

const initialAuth: AuthSnapshot = {
  isConnected: false,
  profile: null,
  step: "connect",
};

const initialProgress: Progress = { current: 0, total: 0, label: "" };

export default function Paste2PlaylistClient() {
  const [auth, setAuth] = useState<AuthSnapshot>(() => {
    const token = getToken();
    const storedProfile = getStoredProfile();
    if (token && storedProfile) {
      return { isConnected: true, profile: storedProfile, step: "input" };
    }
    return initialAuth;
  });
  const [mode, setMode] = useState<InputMode>("album");

  const [albumInput, setAlbumInput] = useState("");
  const [playlistName, setPlaylistName] = useState("My Albums");
  const [playlistDescription, setPlaylistDescription] = useState(
    "Generated by Paste2Playlist"
  );
  const [isPublic, setIsPublic] = useState(false);

  const [processingPhase, setProcessingPhase] =
    useState<ProcessingPhase>("parsing");
  const [progress, setProgress] = useState<Progress>(initialProgress);
  const [matchResults, setMatchResults] = useState<MatchResult[]>([]);

  const [playlistUrl, setPlaylistUrl] = useState("");
  const [totalTracks, setTotalTracks] = useState(0);
  const [error, setError] = useState("");

  const setStep = useCallback((value: SetStateAction<Step>) => {
    setAuth((prev) => {
      const next =
        typeof value === "function"
          ? (value as (prevStep: Step) => Step)(prev.step)
          : value;
      return { ...prev, step: next };
    });
  }, []);

  useEffect(() => {
    const token = getToken();
    const storedProfile = getStoredProfile();
    if (!token || !storedProfile) return;

    // validate/refresh profile asynchronously
    let mounted = true;
    getMe(clientId)
      .then((fresh) => {
        if (mounted) {
          setAuth({ isConnected: true, profile: fresh, step: "input" });
        }
      })
      .catch(() => {
        clearToken();
        if (mounted) {
          setAuth(initialAuth);
        }
      });

    return () => {
      mounted = false;
    };
  }, []);

  const handleConnect = useCallback(async () => {
    const { verifier, challenge } = await createPkcePair();
    const state = generateRandomString(16);

    sessionStorage.setItem("spotify_code_verifier", verifier);
    sessionStorage.setItem("spotify_auth_state", state);

    const authUrl = buildAuthorizeUrl(clientId, redirectUri, state, challenge);
    window.location.href = authUrl;
  }, []);

  const handleDisconnect = useCallback(() => {
    clearToken();
    setAuth(initialAuth);

    setAlbumInput("");
    setMatchResults([]);
    setPlaylistUrl("");
    setTotalTracks(0);
    setError("");

    setProcessingPhase("parsing");
    setProgress(initialProgress);
    setMode("album");
  }, []);

  const handleCreatePlaylist = useCallback(() => {
    void runCreatePlaylistFlow({
      mode,
      albumInput,
      profile: auth.profile,
      playlistName,
      playlistDescription,
      isPublic,
      clientId,
      setError,
      setStep,
      setProcessingPhase,
      setMatchResults,
      setProgress,
      setTotalTracks,
      setPlaylistUrl,
    });
  }, [
    mode,
    albumInput,
    auth.profile,
    playlistName,
    playlistDescription,
    isPublic,
    setError,
    setStep,
    setProcessingPhase,
    setMatchResults,
    setProgress,
    setTotalTracks,
    setPlaylistUrl,
  ]);

  return (
    <div>
      <Header
        isConnected={auth.isConnected}
        profile={auth.profile}
        onDisconnect={handleDisconnect}
      />

      <div className="container mx-auto max-w-3xl space-y-8 px-4 py-8 sm:py-16">
        {!auth.isConnected && <Hero />}
        <ErrorAlert message={error} />

        <StepIndicator step={auth.step} isConnected={auth.isConnected} />

        {auth.step === "connect" && <ConnectButton onConnect={handleConnect} />}

        {auth.step === "input" && (
          <InputCard
            mode={mode}
            setMode={setMode}
            albumInput={albumInput}
            setAlbumInput={setAlbumInput}
            playlistName={playlistName}
            setPlaylistName={setPlaylistName}
            playlistDescription={playlistDescription}
            setPlaylistDescription={setPlaylistDescription}
            isPublic={isPublic}
            setIsPublic={setIsPublic}
            onCreate={handleCreatePlaylist}
          />
        )}

        {auth.step === "processing" && (
          <ProcessingCard
            processingPhase={processingPhase}
            progress={progress}
            matchResults={matchResults}
          />
        )}

        {auth.step === "results" && (
          <ResultsView
            matchResults={matchResults}
            playlistUrl={playlistUrl}
            totalTracks={totalTracks}
            createAnotherHref="/"
          />
        )}

        <div className="mt-8 p-3">
          <p className="text-center text-xs text-muted-foreground">
            We only request permission to create playlists. Your data stays
            private.
          </p>
        </div>
      </div>
    </div>
  );
}
