"use client";

import { useMemo } from "react";
import { ListMusic } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import type { InputMode, Setter } from "@/lib/types";

interface InputCardProps {
  mode: InputMode;
  setMode: Setter<InputMode>;
  albumInput: string;
  setAlbumInput: Setter<string>;
  playlistName: string;
  setPlaylistName: Setter<string>;
  playlistDescription: string;
  setPlaylistDescription: Setter<string>;
  isPublic: boolean;
  setIsPublic: (v: boolean) => void;
  onCreate: () => void;
}

export default function InputCard(props: InputCardProps) {
  const {
    mode,
    setMode,
    albumInput,
    setAlbumInput,
    playlistName,
    setPlaylistName,
    playlistDescription,
    setPlaylistDescription,
    isPublic,
    setIsPublic,
    onCreate,
  } = props;

  const { description, placeholder, title } = useMemo(() => {
    const description =
      mode === "album"
        ? "Enter one album per line in the format: Artist - Album"
        : "Enter one per line in the format: Artist - Year (we will resolve it to Artist - Album)";

    const placeholder =
      mode === "album"
        ? `Example:\nRadiohead - OK Computer\nKendrick Lamar – DAMN.\nTaylor Swift — 1989`
        : `Example:\nTurnstile - 2025\nTyler, The Creator - 2025\nThe Acacia Strain — 2025`;

    const title =
      mode === "album"
        ? "Paste Your Album List"
        : "Paste Your Artist-Year List";
    return { description, placeholder, title };
  }, [mode]);

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <ListMusic className="size-5" />
          {title}
        </CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>

      <CardContent className="space-y-6">
        <div className="flex items-center justify-between rounded-md border border-border p-3">
          <div className="space-y-0.5">
            <p className="text-sm font-medium">Input Mode</p>
            <p className="text-xs text-muted-foreground">
              {mode === "album"
                ? "Artist - Album"
                : "Artist - Year (auto-resolves to full-length album for that year)"}
            </p>
          </div>

          <div className="flex items-center gap-2">
            <Label
              htmlFor="mode-toggle"
              className="text-xs text-muted-foreground"
            >
              Album
            </Label>
            <Switch
              id="mode-toggle"
              checked={mode === "year"}
              onCheckedChange={(checked) => setMode(checked ? "year" : "album")}
            />
            <Label
              htmlFor="mode-toggle"
              className="text-xs text-muted-foreground"
            >
              Year
            </Label>
          </div>
        </div>

        <div>
          <Textarea
            placeholder={placeholder}
            value={albumInput}
            onChange={(e) => setAlbumInput(e.target.value)}
            className="min-h-50 font-mono text-sm"
          />
          <p className="mt-2 text-xs text-muted-foreground">
            Supports various dash types: - – — (hyphen, en-dash, em-dash)
          </p>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="playlist-name">Playlist Name</Label>
            <Input
              id="playlist-name"
              value={playlistName}
              onChange={(e) => setPlaylistName(e.target.value)}
              placeholder="My Albums"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="playlist-description">Description</Label>
            <Input
              id="playlist-description"
              value={playlistDescription}
              onChange={(e) => setPlaylistDescription(e.target.value)}
              placeholder="Generated by Paste2Playlist"
            />
          </div>
        </div>

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Switch
              id="visibility"
              checked={isPublic}
              onCheckedChange={setIsPublic}
            />
            <Label htmlFor="visibility">
              {isPublic ? "Public" : "Private"} playlist
            </Label>
          </div>

          <Button
            onClick={onCreate}
            className="bg-[#1DB954] text-white hover:bg-[#1ed760]"
          >
            Create Playlist
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
