"use client";

import { ListMusic } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";

interface InputCardProps {
  albumInput: string;
  setAlbumInput: (v: string) => void;
  playlistName: string;
  setPlaylistName: (v: string) => void;
  playlistDescription: string;
  setPlaylistDescription: (v: string) => void;
  isPublic: boolean;
  setIsPublic: (v: boolean) => void;
  onCreate: () => void;
}

export default function InputCard({
  albumInput,
  setAlbumInput,
  playlistName,
  setPlaylistName,
  playlistDescription,
  setPlaylistDescription,
  isPublic,
  setIsPublic,
  onCreate,
}: InputCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <ListMusic className="size-5" />
          Paste Your Album List
        </CardTitle>
        <CardDescription>
          Enter one album per line in the format: Artist - Album
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-6">
        <div>
          <Textarea
            placeholder={`Example:\nRadiohead - OK Computer\nKendrick Lamar – DAMN.\nTaylor Swift — 1989`}
            value={albumInput}
            onChange={(e) => setAlbumInput(e.target.value)}
            className="min-h-50 font-mono text-sm"
          />
          <p className="mt-2 text-xs text-muted-foreground">
            Supports various dash types: - – — (hyphen, en-dash, em-dash)
          </p>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="playlist-name">Playlist Name</Label>
            <Input
              id="playlist-name"
              value={playlistName}
              onChange={(e) => setPlaylistName(e.target.value)}
              placeholder="My Albums"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="playlist-description">Description</Label>
            <Input
              id="playlist-description"
              value={playlistDescription}
              onChange={(e) => setPlaylistDescription(e.target.value)}
              placeholder="Generated by Paste2Playlist"
            />
          </div>
        </div>

        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Switch
              id="visibility"
              checked={isPublic}
              onCheckedChange={setIsPublic}
            />
            <Label htmlFor="visibility">
              {isPublic ? "Public" : "Private"} playlist
            </Label>
          </div>

          <Button
            onClick={onCreate}
            className="bg-[#1DB954] text-white hover:bg-[#1ed760]"
          >
            Create Playlist
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
